// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw_H4OxK4sMniGxNqlAmzs0rEEQF4FM5U',
    appId: '1:382872971175:web:32cb59a1cfca0451f8b882',
    messagingSenderId: '382872971175',
    projectId: 'scout-app-5ce6e',
    authDomain: 'scout-app-5ce6e.firebaseapp.com',
    storageBucket: 'scout-app-5ce6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQtOpaOYwDgMcb3JO5UP6ff71xIRPFWDk',
    appId: '1:382872971175:android:37e375b6792ba837f8b882',
    messagingSenderId: '382872971175',
    projectId: 'scout-app-5ce6e',
    storageBucket: 'scout-app-5ce6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKxoEYyZMYN9YzzFdPh_HCY8EtvLuVA5A',
    appId: '1:382872971175:ios:08c325fc9275d2dbf8b882',
    messagingSenderId: '382872971175',
    projectId: 'scout-app-5ce6e',
    storageBucket: 'scout-app-5ce6e.firebasestorage.app',
    iosBundleId: 'com.example.scoutApp',
  );
}
